CREATE TABLE XLATE (
    LANGUAGE_1 CHARACTER (40),
    LANGUAGE_2 CHARACTER VARYING (40) CHARACTER SET GREEK,
    LANGUAGE_3 NATIONAL CHARACTER (40),
    LANGUAGE_4 CHARACTER (40) CHARACTER SET KANJI
) ;