CREATE DATABASE testDb;
DROP DATABASE testDb;
USE testDb;

CREATE TABLE CUSTOMERS (
    ID  INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(25),
    SALARY DECIMAL (18, 2),
    PRIMARY KEY (ID)
);