CREATE TABLE CUSTOMERS (
    ID INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(25),
    SALARY DECIMAL(18, 2) DEFAULT 5000.00,
    PRIMARY KEY (ID)
);

ALTER TABLE CUSTOMERS
    MODIFY SALARY DECIMAL (18, 2) DEFAULT 5000.00;
    
ALTER TABLE customers
    ALTER COLUMN salary DROP DEFAULT;